version: "2"
services:
  mongo:
    image: mongo:latest
    ports:
      - 27017
    volumes:
      - /data/db
    restart: unless-stopped
  app:
    build: .
    ports:
      - 80:3000
    volumes:
      - ".:/app"
    restart: on-failure
    depends_on:
      - mongo
